require 'rails_helper'
require 'factories'

def fill_in_fields (options = {})
  fill_in 'environment_property_name', with: options[:environment_property_name] if options.has_key? :environment_property_name
  fill_in 'environment_property_description', with: options[:environment_property_description] if options.has_key? :environment_property_description
  fill_in 'environment_property_key', with: options[:environment_property_key] if options.has_key? :environment_property_key
end

feature 'Environment property' do

  before(:all) do |example|
    set_module example.class.description
  end

  before(:each) do |example|
    user_login
  end

  after(:each) do |example|
    generate_screenshot example.description.parameterize
  end

  scenario 'Saving blank Environment property form should return an error', :js => true do
    add_new_module_item do
      click_button "Save"
      within ('div.alert-danger') do
        expect(page).to have_content "#{@module_info[:name]} failed to be created"
        expect(page).to have_content "- Name can't be blank"
        expect(page).to have_content "- Key can't be blank"
        expect(page).to have_content "- Key should contain alpha numeric and underscore characters only"
      end
    end
  end

  scenario 'Cancelling add should return no actions were taken', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description",
      })
      click_button "Cancel"
      within ('div.alert-info') { expect(page).to have_content("No actions were taken") }
    end
  end

  scenario 'Adding Environment property with required fields should work', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
    end
  end

  scenario 'Save and Add another should save Environment property and remain in the Environment property form page', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save and add another"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
      expect(page).to have_content "New #{@module_info[:name]}"
    end
  end

  scenario 'Save and Edit button should save Environment property record and remain in filled-up form page', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save and edit"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
      expect(page).to have_content "Edit #{@module_info[:name]}"
    end
  end

  scenario 'Saving duplicate name and key should not work', :js => true do
    environment_property = FactoryBot.create :environment_property, application: @application
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save and edit"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
      expect(page).to have_field "environment_property_name", with: "Test Environment property"
      expect(page).to have_field "environment_property_description", with: "Test Environment property description"
      expect(page).to have_field "environment_property_key", with: "test_environment_property"
    end

    check "override_key"
    within "#environment_property_key_field" do
      expect(page).to have_field "environment_property_key", readonly: false
      expect(page).to have_checked_field "override_key"
    end
    fill_in_fields ({
        environment_property_name: environment_property.name,
        environment_property_key: environment_property.key
    })
    click_button "Save and edit"
    within ('div.alert-danger') do
      expect(page).to have_content "#{@module_info[:name]} failed to be updated"
      expect(page).to have_content "- Name has already been taken"
      expect(page).to have_content "- Key has already been taken. Note: key is generated by converting name to lowercase and symbols to underscores by default."
    end

  end

  scenario 'Clicking Show should allow user to view Environment property information', :js => true do
    environment_property = FactoryBot.create :environment_property, application: @application
    visit "/admin"
    go_to_module_dashboard
    find_and_show environment_property.name
    expect(page).to have_content "Details for #{@module_info[:name]} '#{environment_property.name}'"
  end

  scenario 'Clicking Edit should allow user to update Environment property information', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
    end

    visit "/admin"
    go_to_module_dashboard
    find_and_edit "Test Environment property"
    fill_in_fields ({
        environment_property_name: "Test Environment property new name",
        environment_property_description: "Test Environment property new description"
    })
    click_button "Save and edit"
    expect(page).to have_content "#{@module_info[:name]} successfully updated"
    expect(page).to have_field "environment_property_name", with: "Test Environment property new name"
    expect(page).to have_field "environment_property_description", with: "Test Environment property new description"
  end

  scenario 'Cancelling delete should not remove Environment property record from list', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
    end

    visit "/admin"
    go_to_module_dashboard
    find_and_edit "Test Environment property"
    within ('ul.nav-tabs') { click_link 'Delete' }
    expect(page).to have_content "Delete #{@module_info[:name]} 'Test Environment property'"

    click_button "Cancel"
    within ('div.alert-info') { expect(page).to have_content("No actions were taken") }
    expect(page).to have_content "Edit #{@module_info[:name]} 'Test Environment property'"
  end

  scenario 'Deleting Environment property object should remove data from list', :js => true do
    add_new_module_item do
      fill_in_fields ({
          environment_property_name: "Test Environment property",
          environment_property_description: "Test Environment property description"
      })
      click_button "Save"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
    end

    find_and_edit "Test Environment property"
    within ('ul.nav-tabs') { click_link 'Delete' }
    expect(page).to have_content "Delete #{@module_info[:name]} 'Test Environment property'"

    click_button "Yes, I'm sure"
    within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully deleted") }
  end

  scenario 'Environment property added should appear in environment object', :js => true do
    add_new_module_item do
      fill_in_fields ({ environment_property_name: "Test Environment property", environment_property_description: "Test Environment property description" })
      click_button "Save and edit"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
      expect(page).to have_field "environment_property_key", with: "test_environment_property"
    end

    @module_info = { name: "Environment", name_plural: "Environments", url: "/admin/environment?locale=en", navbar_path: ["Environments", "Environments"], via: "nav_path" }
    environment = FactoryBot.create :environment, name: "test", key: "test", application: @application
    find_and_edit environment.name
    expect(page).to have_field "environment[environment_property_list[test_environment_property]]"
  end

  scenario 'Environment property edited should also be updated in environment object' do
    add_new_module_item do
      fill_in_fields ({ environment_property_name: "Test Environment property", environment_property_description: "Test Environment property description" })
      click_button "Save and edit"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
      expect(page).to have_field "environment_property_key", with: "test_environment_property"
    end

    @module_info = { name: "Environment", name_plural: "Environments", url: "/admin/environment?locale=en", navbar_path: ["Environments", "Environments"], via: "nav_path" }
    environment = FactoryBot.create :environment, name: "test", key: "test", application: @application
    find_and_edit environment.name
    expect(page).to have_field "environment[environment_property_list[test_environment_property]]"

    @module_info = { name: "Environment property", name_plural: "Environment properties", url: "/admin/environment_property?locale=en", navbar_path: ["Environments", "Environment properties"], via: "nav_path" }
    find_and_edit "Test Environment property"
    fill_in_fields ({ environment_property_name: "Test updated Environment property" })
    check "override_key"
    within "#environment_property_key_field" do
      expect(page).to have_field "environment_property_key", readonly: false
      expect(page).to have_checked_field "override_key"
    end
    fill_in_fields ({ environment_property_key: "test_environment_property_new_key" })
    click_button "Save"
    within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully updated") }

    @module_info = { name: "Environment", name_plural: "Environments", url: "/admin/environment?locale=en", navbar_path: ["Environments", "Environments"], via: "nav_path" }
    find_and_edit environment.name
    expect(page).to have_field "environment[environment_property_list[test_environment_property_new_key]]"
    @module_info = { name: "Environment property", name_plural: "Environment properties", url: "/admin/environment_property?locale=en", navbar_path: ["Environments", "Environment properties"], via: "nav_path" } # This is for the screenshot path
  end

  scenario 'Environment property deleted should be removed from the list of environment properties in environment object' do
    add_new_module_item do
      fill_in_fields ({ environment_property_name: "Test Environment property", environment_property_description: "Test Environment property description" })
      click_button "Save and edit"
      within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully created") }
      expect(page).to have_field "environment_property_key", with: "test_environment_property"
    end

    @module_info = { name: "Environment", name_plural: "Environments", url: "/admin/environment?locale=en", navbar_path: ["Environments", "Environments"], via: "nav_path" }
    environment = FactoryBot.create :environment, name: "test", key: "test", application: @application
    find_and_edit environment.name
    expect(page).to have_field "environment[environment_property_list[test_environment_property]]"

    @module_info = { name: "Environment property", name_plural: "Environment properties", url: "/admin/environment_property?locale=en", navbar_path: ["Environments", "Environment properties"], via: "nav_path" }
    find_and_edit "Test Environment property"

    within ('ul.nav-tabs') { click_link 'Delete' }
    expect(page).to have_content "Delete #{@module_info[:name]} 'Test Environment property'"

    click_button "Yes, I'm sure"
    within ('div.alert-success') { expect(page).to have_content("#{@module_info[:name]} successfully deleted") }

    @module_info = { name: "Environment", name_plural: "Environments", url: "/admin/environment?locale=en", navbar_path: ["Environments", "Environments"], via: "nav_path" }
    find_and_edit environment.name
    expect(page).not_to have_field "environment[environment_property_list[test_environment_property_new_key]]"

  end



end