require 'spec_helper'
require 'factories'

describe 'Schedule', type: :model do

  it 'is not valid when attributes are not defined' do
    sched = Schedule.new
    expect{sched.save!}.to raise_exception(ActiveRecord::RecordInvalid, "Validation failed: Name can't be blank, Key can't be blank, Key should contain alpha numeric and underscore characters only")
  end

  it 'is not valid when name is empty' do
    sched = Schedule.new(:key => 'sched')
    expect{sched.save!}.to raise_exception(ActiveRecord::RecordInvalid, "Validation failed: Name can't be blank")
  end

  it 'is not valid when key is numeric' do
    sched = Schedule.new(:name => 'sched', :key => '1')
    expect{sched.save!}.to raise_exception(ActiveRecord::RecordInvalid, "Validation failed: Key should contain alpha numeric and underscore characters only")
  end

  it 'is only valid when name and key are defined' do
    sched = Schedule.new(:name => 'sched', :key => 'sched')
    expect(sched).to be_valid
  end

  it 'is not valid when name has a duplicate' do
    @application = FactoryBot.create(:application)
    sched = Schedule.new(:name => 'sched', :key => 'sched', application: @application)
    sched.save!
    sched2 = Schedule.new(:name => 'sched', :key => 'sched', application: @application)
    expect{sched2.save!}.to raise_exception(ActiveRecord::RecordInvalid, "Validation failed: Name has already been taken, Key has already been taken. Note: key is generated by converting name to lowercase and symbols to underscores by default.")

  end


end